### ISSUE TITLE
希望Xray-core更新的时候不更新xray.service，User给的root权限，更新后又变成了nobody

### ISSUE THREAD

**Issue by C222l** [XTLS/Xray-install#3]
希望Xray-core更新的时候不更新xray.service，User给的root权限，更新后又变成了nobody，每次更新后都需要手动改一下。

**Comment by badO1a5A90** [comment]
https://github.com/XTLS/Xray-install/tree/dev

自动识别用户
不会覆盖用户修改的dev分支

安装时把main换成dev即可

**Comment by mclovin-2k** [comment]
我觉得应该引导用户将修改内容放在 /etc/systemd/system/xray.service.d/ 下。类似于目前 multiple configuration files 的实现方式。

**Comment by mclovin-2k** [comment]
目前只要执行一行命令即可ROOT用户运行，并且不会被更新覆盖。
`echo -e "[Service]\nUser=\nUser=root" > /etc/systemd/system/xray.service.d/user_root.conf && systemctl daemon-reload`
并不需要什么自动识别。

**Comment by xiaoyaoyuxin** [comment]
> 目前只要执行一行命令即可ROOT用户运行，并且不会被更新覆盖。
> `echo -e "[Service]\nUser=\nUser=root" > /etc/systemd/system/xray.service.d/09-user_root.conf && systemctl daemon-reload`
> 并不需要什么自动识别。

感谢！！
systemd的服务配置文件，是可以从多个文件加载的?

**Comment by mclovin-2k** [comment]
> > 目前只要执行一行命令即可ROOT用户运行，并且不会被更新覆盖。
> > `echo -e "[Service]\nUser=\nUser=root" > /etc/systemd/system/xray.service.d/09-user_root.conf && systemctl daemon-reload`
> > 并不需要什么自动识别。
> 
> 感谢！！
> systemd的服务配置文件，是可以从多个文件加载的?

YES

**Comment by xiaoyaoyuxin** [comment]
> > > 目前只要执行一行命令即可ROOT用户运行，并且不会被更新覆盖。
> > > `echo -e "[Service]\nUser=\nUser=root" > /etc/systemd/system/xray.service.d/09-user_root.conf && systemctl daemon-reload`
> > > 并不需要什么自动识别。
> > 
> > 
> > 感谢！！
> > systemd的服务配置文件，是可以从多个文件加载的?
> 
> YES

但应用以后，修改回默认的证书位置，还是报错……

● xray.service - Xray Service
   Loaded: loaded (/etc/systemd/system/xray.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/xray.service.d
           └─09-user_root.conf, 10-donot_touch_single_conf.conf
   Active: failed (Result: exit-code) since Sun 2020-12-27 10:14:36 CST; 3s ago
     Docs: https://github.com/xtls
  Process: 10481 ExecStart=/usr/local/bin/xray run -config /usr/local/etc/xray/config.json (code=exited, status=1/FAILURE)
 Main PID: 10481 (code=exited, status=1/FAILURE)

Dec 27 10:14:36 bwg11 systemd[1]: Started Xray Service.
Dec 27 10:14:36 bwg11 xray[10481]: Xray 1.1.4 (Xray, Penetrates Everything.) Custom (go1.15.6 linux/amd64)
Dec 27 10:14:36 bwg11 xray[10481]: A unified platform for anti-censorship.
Dec 27 10:14:36 bwg11 xray[10481]: 2020/12/27 10:14:36 [Info] main/jsonem: Reading config: /usr/local/etc/xray/config.json
Dec 27 10:14:36 bwg11 xray[10481]: Failed to start: main: failed to load config files: [/usr/local/etc/xray/config.json] > infra/conf: Fail...on denied
Dec 27 10:14:36 bwg11 systemd[1]: xray.service: main process exited, code=exited, status=1/FAILURE
Dec 27 10:14:36 bwg11 systemd[1]: Unit xray.service entered failed state.
Dec 27 10:14:36 bwg11 systemd[1]: xray.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by rprx** [comment]
请使用最新的脚本 https://github.com/XTLS/Xray-install
